demos:
  deploy_application:
    name: "Deploy Application (survey)"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Ansible official demo project"
    playbook: "01_deploy_application.yml"
    credential: "Demo Credential"
    survey_enabled: yes
    survey_spec: "{{ lookup('file', 'my_survey.json') }}"
    workshop_type:
      - f5
      - rhel
