- name: create HTML report
  become: yes
  template:
    src: report.j2
    dest: "{{ file_path }}"

- name: DISPLAY LINK TO INVENTORY REPORT
  debug:
    msg: "Please go to http://{{ansible_host}}/report"
