---
- name: add tower project
  tower_project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Buisness Unit"
    organization: "Default"
    scm_type: git
    scm_url: https://github.com/ansible/product-demos
    tower_username: "{{my_tower_username}}"
    tower_password: "{{my_tower_password}}"
    tower_host: "{{my_tower_host}}"
    validate_certs: no

- name: print out values
  debug:
    msg: "{{demos["demo"].name}}"
# - name: add deploy application job template
#   tower_job_template:
#     name: "{{demos["demo"].name}}"
#     job_type: "{{job_type}}"
#     inventory: "{{inventory}}"
#     project: "{{project}}"
#     playbook: "{{playbook}}"
#     credential: "{{credential}}"
#     survey_enabled: "{{survey_enabled}}"
#     survey_spec: "{{survey_spec}}"
#     tower_username: "{{my_tower_username}}"
#     tower_password: "{{my_tower_password}}"
#     tower_host: "{{my_tower_host}}"
#     validate_certs: no
