---
- name: provide info to terminal window
  debug:
    msg: "install {{demo}} on {{my_tower_host}}"

# - name: install all job templates
#   include: add_job_template.yml
#   loop: "{{ demos|dict2items }}"
#   when: demo == "all"

- name: install single job template
  include: single_job_template.yml
  when: demo != "all"
