---
- name: add tower project
  tower_project:
    name: "Ansible official demo project"
    description: "prescriptive demos from Red Hat Management Buisness Unit"
    organization: "Default"
    scm_type: git
    scm_url: https://github.com/ansible/product-demos
    tower_username: "{{my_tower_username}}"
    tower_password: "{{my_tower_password}}"
    tower_host: "{{my_tower_host}}"
    validate_certs: no

- name: install all job templates
  include: add_job_template.yml
  loop: "{{ demos|dict2items }}"
  when: demo == "all"

- name: install single job template
  include: single_job_template.yml
  when: demo != "all"
