- name: add tower project
  tower_project:
    name: "{{project.my_name}}"
    description: "{{project.my_description}}"
    organization: "{{project.my_organization}}"
    scm_type: "{{project.my_scm_type}}"
    scm_url: "{{project.my_scm_url}}"
    tower_username: "{{my_tower_username}}"
    tower_password: "{{my_tower_password}}"
    tower_host: "{{my_tower_host}}"
    validate_certs: no

- name: add single job template without survey
  tower_job_template:
    name: "{{demos[demo].name}}"
    job_type: "{{demos[demo].job_type}}"
    inventory: "{{demos[demo].inventory}}"
    project: "{{demos[demo].project}}"
    playbook: "{{demos[demo].playbook}}"
    credential: "{{demos[demo].credential}}"
    survey_enabled: "{{demos[demo].survey_enabled}}"
    tower_username: "{{my_tower_username}}"
    tower_password: "{{my_tower_password}}"
    tower_host: "{{my_tower_host}}"
    validate_certs: no
  when:
    - not demos[demo].survey_enabled

- name: add single job template with survey
  tower_job_template:
    name: "{{demos[demo].name}}"
    job_type: "{{demos[demo].job_type}}"
    inventory: "{{demos[demo].inventory}}"
    project: "{{demos[demo].project}}"
    playbook: "{{demos[demo].playbook}}"
    credential: "{{demos[demo].credential}}"
    survey_enabled: "{{demos[demo].survey_enabled}}"
    survey_spec: "{{demos[demo].survey_spec}}"
    tower_username: "{{my_tower_username}}"
    tower_password: "{{my_tower_password}}"
    tower_host: "{{my_tower_host}}"
    validate_certs: no
  when:
    - demos[demo].survey_enabled
