---
survey_deploy_application:
  name: Deploy application survey
  description: Which application do you want to install?
  spec:
  - type: multiplechoice
    question_name: Select a command you would like to execute
    question_description: select the application
    variable: application
    required: true
    default: httpd
    choices:
      - httpd
      - nginx
      - htop
      - gdb
