---
demos:
  deploy_application:
    name: "Deploy Application (survey)"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Ansible official demo project"
    playbook: "playbooks/01_deploy_application.yml"
    credential: "Demo Credential"
    survey_enabled: yes
    survey_spec: "{{survey_deploy_application}}"
    workshop_type:
      - f5
      - rhel
