demos:
  deploy_application:
    name: "Deploy Application (survey)"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Ansible official demo project"
    playbook: "playbooks/01_deploy_application.yml"
    credential: "Workshop Credential"
    survey_enabled: yes
    survey_spec: "{{survey_deploy_application}}"
    workshop_type:
      - f5
      - rhel
  windows_iis:
    name: "Windows IIS Server"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Ansible official demo project"
    playbook: "playbooks/05_windows_iis.yml"
    credential: "Demo Credential"
    survey_enabled: no
    workshop_type:
      - windows
  openscap:
    name: "Create Openscap Report"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Ansible official demo project"
    playbook: "playbooks/10_openscap.yml"
    credential: "Workshop Credential"
    survey_enabled: no
    workshop_type:
      - f5
      - rhel
  developer_report:
    name: "Create Developer Report"
    job_type: "run"
    inventory: "Workshop Inventory"
    project: "Ansible official demo project"
    playbook: "playbooks/11_developer_report.yml"
    credential: "Workshop Credential"
    survey_enabled: no
    workshop_type:
      - f5
      - rhel
