---
galaxy_info:
  role_name: install_demo
  author: Sean Cavanaugh
  description: |
    This role will install demos into your specified Ansible Tower environment.
  company: Red Hat


  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.9

  galaxy_tags: []
dependencies: []
