---
galaxy_info:
  role_name: developer_report
  author: Sean Cavanaugh
  description: This role create an HTML report using Ansible Facts
  company: Red Hat


  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 2.9

  galaxy_tags: []

dependencies: []
