- name: Create HTML report
  ansible.builtin.template:
    src: report.j2
    dest: "{{ file_path }}/windows.html"

- name: Copy CSS over
  ansible.builtin.copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true

- name: Copy logos over
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ file_path }}"
    directory_mode: true
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "server.png"

- name: Display link to inventory report
  ansible.builtin.debug:
    msg: "Please go to http://{{ ansible_host }}/windows.html"
