---
- hosts: "{{ 'reports' | default(node1) }}"
  
  tasks:
  - yum:
      name: httpd

  - service:
      name: httpd
      state: started

  - include_role:
      name: demo.patching.build_report_linux