---
- hosts: "{{ HOSTS }}"
  become: yes
  vars:
    report_server: node1
  
  tasks:
  - include_role:
      name: demo.patching.patch_linux

  - block:
    - yum:
        name: httpd
        state: latest
      check_mode: no

    - service:
        name: httpd
        state: started
      check_mode: no

    - include_role:
        name: demo.patching.report_linux

    - include_role:
        name: demo.patching.report_linux_patching
    delegate_to: "{{ report_server }}"
    run_once: yes