---
- name: grab linux facts
  hosts: all
  gather_facts: true

- name: build developer report
  hosts: node1
  gather_facts: false

  vars:
    file_path: /var/www/html/report/index.html

  tasks:
    - name: use developer report
      include_role:
        name: developer_report
